### ISSUE TITLE
Integrating fast RIR in Lhotse

### ISSUE THREAD

**Issue by desh2608** [yluo42/FRA-RIR#1]
I came across your paper on ArXiv, and the method looks quite promising. I am interested in integrating this as a data transform in Lhotse (https://github.com/lhotse-speech/lhotse/discussions/787). However, my concern is that this code is distributed under a CC-by-NC license, whereas Lhotse provides an Apache license. Of course, there would be a significant rewrite in the integration itself, but the core implementation would be the same. I am not sure if this would be an issue?

**Comment by yluo42** [comment]
Hi Desh, thanks for your interest in this work! I'm currently checking with my team and the company here regarding the license, and I will try to get back to you ASAP.

**Comment by yluo42** [comment]
Hey Desh, after some discussion here it is allowed that the code can be released under Apache license. I have already changed the license in the repo, please feel free to clone it as needed. It would also be great if you can first validate its performance in your tasks and data and then decide whether to merge it into your pipelines.

**Comment by desh2608** [comment]
Hi Yi, thanks for looking into this! I will add the functionality to Lhotse next month (I'm on an internship at the moment) and see if it helps my pipelines. In any case, it shouldn't hurt to have it as an option, since Lhotse is a fairly general data preparation tool.

**Comment by desh2608** [comment]
This method is now available in Lhotse: https://github.com/lhotse-speech/lhotse/pull/799

**Comment by yluo42** [comment]
Thanks for the work Desh! We will also take a look at Lhotse and see if we can also make use of it or contribute to it. Also looking forwarding to seeing your experiment results on FRA-RIR vs. fixed RIR dataset!
