### ISSUE TITLE
Is multi mic supported?

### ISSUE THREAD

**Issue by xinkez** [yluo42/FRA-RIR#2]
hi, I came across your paper on ArXiv, and your idea looks great. is multi mic supported? or, how can it be extended to muti mic (mic array simulation)? thank you in advance.

**Comment by yluo42** [comment]
Hi, thanks for your interested in our work. The extension to mic arrays needs some further modifications and validations in the approximation part, and we will make an update here when we finish them. Stay tuned!

**Comment by xinkez** [comment]
Got it. Thanks.
