### ISSUE TITLE
Something dismatching with paper in code .

### ISSUE THREAD

**Issue by wangers** [yluo42/FRA-RIR#3]
In line 85/86 of[(https://github.com/tencent-ailab/FRA-RIR/blob/main/FRA-RIR.py)]
`    for i in range(nsource):
        rir[i][delta_idx[i]] += delta_decay[i]`
and `delta_idx` is treated as an sample index, however, as the paper descreibe:
>   the number of distant virtual sound sources increases as their distance increases

the matrix delta_decay may have some different values but point to the same distance.
but the above code just keed the last `delta_idx[i]`, **i.e., if `delta_idx[i]==delta_idx[j]`, 
it just keep one of them**. I'm confused with this and want to know is it true?

line 75

>   `reflect_pertub = torch.FloatTensor(nsource, image).uniform_(a, b) * dist_ratio.pow(tau)`

In paper `dist_ratio` denotes distance but here is `dist/d_0`

line 58> `dist_range = [torch.linspace(1., velocity*T60/direct_dist[i]-1, image) for i in range(nsource)]`
range should be `[1, c_{0}T_{60}/d_{0}]`, i guess.

**Comment by yluo42** [comment]
Dear wangers, many thanks for pointing out these inconsistencies! For (1), that was indeed not expected and we were not aware of that when we implemented it. For (3), yes the minus 1 part is unnecessary. We have fixed them in the lasted commit. For (2), our intention is to use the distance ratio to control the pertubation, and we will fix the description in the paper.
