### ISSUE TITLE
仿真生成的数据异常问题

### ISSUE THREAD

**Issue by maoyapeng** [yluo42/FRA-RIR#4]
仿真8麦克风线阵，间距35mm,采用生成的rir进行数据合成，发现合成的数据每个通之间没有明显的时延差。以下是我的调用与配置
    d = 0.035
    mic_arch = [
    [0, -3.5*d, 0],
    [0, -2.5*d, 0],
    [0, -1.5*d, 0],
    [0, -0.5*d, 0],
    [0, 0.5*d, 0],
    [0, 1.5*d, 0],
    [0, 2.5*d, 0],
    [0, 3.5*d, 0],
    ]
    rt60 = [0.4,0.4]
    room_dim = [8,6,3]
    array_pos = [[2,3,1.5]]
    src2_pos = [[4,1,1.5]] # 45

    array_pos = np.array(array_pos)
    mic_pos = np.array(array_pos) + np.array(mic_arch)

    rir, rir_direct = FRA_RIR_ADHOC(mic_arch,16000,rt60,room_dim,array_pos,src2_pos,mic_pos,num_src=1)
    soundfile.write('/mnt/data/disk_1/rir/rir_1_45.wav', rir[:, 0, :].transpose(1, 0), 16000)
    soundfile.write('/mnt/data/disk_1/rir/rir_45_1_direct.wav', rir_direct[:, 0, :].transpose(1, 0), 16000)

**Comment by Moplast** [comment]
Hi yapeng,
Glad that you are interested in our work. We've just run the configuration you provided, and here is the result:

![企业微信截图_16846774486418](https://github.com/tencent-ailab/FRA-RIR/assets/22789040/73ae664e-e2e0-4faa-9a9f-585d9851a543)

The observed direct sound delay between the first and the eighth channel is about 1.17*7≈8.2 samples at 16k Hz sample rate, which matches the therotical TDOA between these two channels. So it seems nice to me. Could you elaborate on "no obvious delay difference between channels"?

**Comment by maoyapeng** [comment]
你好，很高兴你的解答，合成rir直达声通道间是具有延时信息，但是当我采用rir进行多通道数据生成，发现生成的数据通道间基本没有明显的时延。重复了几次基本都差不多，所以感觉这点有点奇怪，不知道哪里出了问题?
这是我生成的rir:
![1684680654099](https://github.com/tencent-ailab/FRA-RIR/assets/35514873/fba6a848-9ed6-453c-b3fe-f91ee801f7ed)
这是我采用这组rir生成的数据：
![1684681000553](https://github.com/tencent-ailab/FRA-RIR/assets/35514873/4ac1de44-ece7-45a0-be5b-649d7d063391)

**Comment by Moplast** [comment]
If the generated RIRs are correct then it shall be some issue on the convolution between the RIRs and your signal. I'd recommend you double check your code for this part.

**Comment by maoyapeng** [comment]
你好，这里是我数据生成的代码：
clear all;
% 读取多通道的房间冲激响应（RIR）数据
rir_data = audioread('rir_1_45.wav'); 
rir =rir_data'; % 

% 读取单通道的语音信号
speech_data = audioread('clean.wav'); % 

% 确定语音信号的长度
speech_len = length(speech_data);

% 确定通道数
num_channels = size(rir, 1);

% 创建多通道语音矩阵
multi_channel_speech = zeros(speech_len, num_channels);

% 使用RIR将单通道语音信号混合到多个通道
for channel = 1:num_channels
    conv_output = conv(speech_data, rir(channel, :));
    multi_channel_speech(:, channel) = conv_output(1:speech_len);
end

% 将多通道语音保存为WAV文件
audiowrite('multi_channel_speech.wav', multi_channel_speech, 16000);

**Comment by Moplast** [comment]
The code looks correct. I checked again the figure you provided above, and it actually shows the difference bewteen channels right at the place your cursor points at (~0.3055, check the "peaks" for different channels around that time stamp).

**Comment by maoyapeng** [comment]
你好，这是我的数据和合成脚本：
链接: https://pan.baidu.com/s/1zPo-6MFK4avGrznq93M9UA 提取码: wyic
